// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryTotalBetingRequest struct {
}

func (m *QueryTotalBetingRequest) Reset()         { *m = QueryTotalBetingRequest{} }
func (m *QueryTotalBetingRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalBetingRequest) ProtoMessage()    {}
func (*QueryTotalBetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba210adeee9ee5e5, []int{0}
}
func (m *QueryTotalBetingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalBetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalBetingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalBetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalBetingRequest.Merge(m, src)
}
func (m *QueryTotalBetingRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalBetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalBetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalBetingRequest proto.InternalMessageInfo

type QueryTotalBetingResponse struct {
	Balances github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=balances,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"balances"`
}

func (m *QueryTotalBetingResponse) Reset()         { *m = QueryTotalBetingResponse{} }
func (m *QueryTotalBetingResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalBetingResponse) ProtoMessage()    {}
func (*QueryTotalBetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba210adeee9ee5e5, []int{1}
}
func (m *QueryTotalBetingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalBetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalBetingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalBetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalBetingResponse.Merge(m, src)
}
func (m *QueryTotalBetingResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalBetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalBetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalBetingResponse proto.InternalMessageInfo

func (m *QueryTotalBetingResponse) GetBalances() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTotalBetingRequest)(nil), "game.gamemodule.QueryTotalBetingRequest")
	proto.RegisterType((*QueryTotalBetingResponse)(nil), "game.gamemodule.QueryTotalBetingResponse")
}

func init() { proto.RegisterFile("game/query.proto", fileDescriptor_ba210adeee9ee5e5) }

var fileDescriptor_ba210adeee9ee5e5 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0xc7, 0xef, 0x14, 0x45, 0xae, 0x83, 0x7a, 0x0a, 0xb6, 0x45, 0x52, 0xe9, 0x54, 0x87, 0x26,
	0xbd, 0x2a, 0xb8, 0xd7, 0xcd, 0xcd, 0xe2, 0xe4, 0x96, 0xbb, 0x3e, 0xe2, 0xe9, 0x5d, 0xde, 0xb5,
	0xc9, 0x89, 0x1d, 0x5c, 0x14, 0x9c, 0x05, 0xbf, 0x85, 0x9f, 0xa4, 0x63, 0xc1, 0xc5, 0x49, 0xa5,
	0xf5, 0x83, 0x48, 0x2e, 0x87, 0x14, 0x45, 0x70, 0x49, 0x42, 0xfe, 0xff, 0xbc, 0xdf, 0xfb, 0xbf,
	0x78, 0x1b, 0x82, 0xa7, 0xc0, 0x86, 0x39, 0x8c, 0xc6, 0x34, 0x1b, 0xa1, 0x46, 0x7f, 0xdd, 0xdc,
	0x50, 0xb3, 0xa4, 0x38, 0xc8, 0x13, 0xa8, 0x6f, 0x0b, 0x14, 0x58, 0x68, 0xcc, 0x9c, 0xac, 0xad,
	0xbe, 0x2b, 0x10, 0x45, 0x02, 0x8c, 0x67, 0x31, 0xe3, 0x52, 0xa2, 0xe6, 0x3a, 0x46, 0xa9, 0x4a,
	0x95, 0x44, 0xa8, 0x52, 0x54, 0x2c, 0xe4, 0x0a, 0xd8, 0x75, 0x10, 0x82, 0xe6, 0x01, 0x8b, 0x30,
	0x96, 0x56, 0x6f, 0xd6, 0xbc, 0x9d, 0x53, 0xc3, 0x3c, 0x43, 0xcd, 0x93, 0x1e, 0xe8, 0x58, 0x8a,
	0x3e, 0x0c, 0x73, 0x50, 0xba, 0x79, 0xef, 0x7a, 0xd5, 0xdf, 0x9a, 0xca, 0x50, 0x2a, 0xf0, 0x85,
	0xb7, 0x16, 0xf2, 0x84, 0xcb, 0x08, 0x54, 0xd5, 0xdd, 0x5b, 0x6e, 0x55, 0xba, 0x35, 0x6a, 0x51,
	0xd4, 0xa0, 0x68, 0x89, 0xa2, 0xc7, 0x18, 0xcb, 0x5e, 0x67, 0xf2, 0xd6, 0x70, 0x9e, 0xdf, 0x1b,
	0x2d, 0x11, 0xeb, 0x8b, 0x3c, 0xa4, 0x11, 0xa6, 0xac, 0xec, 0xcb, 0x6e, 0x6d, 0x35, 0xb8, 0x62,
	0x7a, 0x9c, 0x81, 0x2a, 0x1e, 0xa8, 0xfe, 0x77, 0xf1, 0xee, 0x83, 0xeb, 0xad, 0x14, 0x5d, 0xf8,
	0xb7, 0x5e, 0x65, 0xa1, 0x13, 0xbf, 0x45, 0x7f, 0xcc, 0x87, 0xfe, 0x11, 0xa4, 0xbe, 0xff, 0x0f,
	0xa7, 0x8d, 0xd5, 0xac, 0xdd, 0xbd, 0x7c, 0x3e, 0x2d, 0x6d, 0xf9, 0x9b, 0xac, 0xf8, 0x0e, 0x6d,
	0x2c, 0x61, 0x61, 0xe9, 0x9d, 0x4c, 0x66, 0xc4, 0x9d, 0xce, 0x88, 0xfb, 0x31, 0x23, 0xee, 0xe3,
	0x9c, 0x38, 0xd3, 0x39, 0x71, 0x5e, 0xe7, 0xc4, 0x39, 0xef, 0x2c, 0xc4, 0x1a, 0x63, 0x2e, 0xc5,
	0x65, 0x2e, 0x83, 0xa3, 0xe0, 0x90, 0x59, 0x5a, 0x5b, 0x83, 0xd2, 0xec, 0xa6, 0xac, 0x68, 0x42,
	0x86, 0xab, 0xc5, 0xf0, 0x0f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0xfa, 0x2a, 0x4e, 0xf5,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	TotalBeting(ctx context.Context, in *QueryTotalBetingRequest, opts ...grpc.CallOption) (*QueryTotalBetingResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TotalBeting(ctx context.Context, in *QueryTotalBetingRequest, opts ...grpc.CallOption) (*QueryTotalBetingResponse, error) {
	out := new(QueryTotalBetingResponse)
	err := c.cc.Invoke(ctx, "/game.gamemodule.Query/TotalBeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	TotalBeting(context.Context, *QueryTotalBetingRequest) (*QueryTotalBetingResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) TotalBeting(ctx context.Context, req *QueryTotalBetingRequest) (*QueryTotalBetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalBeting not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_TotalBeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalBetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalBeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.gamemodule.Query/TotalBeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalBeting(ctx, req.(*QueryTotalBetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "game.gamemodule.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TotalBeting",
			Handler:    _Query_TotalBeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/query.proto",
}

func (m *QueryTotalBetingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalBetingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalBetingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTotalBetingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalBetingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalBetingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Balances) > 0 {
		for iNdEx := len(m.Balances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTotalBetingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTotalBetingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Balances) > 0 {
		for _, e := range m.Balances {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTotalBetingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalBetingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalBetingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalBetingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalBetingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalBetingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balances = append(m.Balances, types.Coin{})
			if err := m.Balances[len(m.Balances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
