// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgBetAmountRequest struct {
	FromAddress string                                   `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty" yaml:"from_address"`
	Betting     string                                   `protobuf:"bytes,2,opt,name=betting,proto3" json:"betting,omitempty" yaml:"betting"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgBetAmountRequest) Reset()         { *m = MsgBetAmountRequest{} }
func (m *MsgBetAmountRequest) String() string { return proto.CompactTextString(m) }
func (*MsgBetAmountRequest) ProtoMessage()    {}
func (*MsgBetAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_497c523f337df817, []int{0}
}
func (m *MsgBetAmountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBetAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBetAmountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBetAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBetAmountRequest.Merge(m, src)
}
func (m *MsgBetAmountRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgBetAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBetAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBetAmountRequest proto.InternalMessageInfo

func (m *MsgBetAmountRequest) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgBetAmountRequest) GetBetting() string {
	if m != nil {
		return m.Betting
	}
	return ""
}

func (m *MsgBetAmountRequest) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgBetAmountResponse struct {
}

func (m *MsgBetAmountResponse) Reset()         { *m = MsgBetAmountResponse{} }
func (m *MsgBetAmountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBetAmountResponse) ProtoMessage()    {}
func (*MsgBetAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_497c523f337df817, []int{1}
}
func (m *MsgBetAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBetAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBetAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBetAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBetAmountResponse.Merge(m, src)
}
func (m *MsgBetAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBetAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBetAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBetAmountResponse proto.InternalMessageInfo

type MsgAllRewardsRequest struct {
	ToAddress string                                   `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty" yaml:"to_address"`
	Winners   string                                   `protobuf:"bytes,2,opt,name=winners,proto3" json:"winners,omitempty" yaml:"winners"`
	Amount    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgAllRewardsRequest) Reset()         { *m = MsgAllRewardsRequest{} }
func (m *MsgAllRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*MsgAllRewardsRequest) ProtoMessage()    {}
func (*MsgAllRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_497c523f337df817, []int{2}
}
func (m *MsgAllRewardsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAllRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAllRewardsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAllRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAllRewardsRequest.Merge(m, src)
}
func (m *MsgAllRewardsRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgAllRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAllRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAllRewardsRequest proto.InternalMessageInfo

func (m *MsgAllRewardsRequest) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgAllRewardsRequest) GetWinners() string {
	if m != nil {
		return m.Winners
	}
	return ""
}

func (m *MsgAllRewardsRequest) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgAllRewardsResponse struct {
}

func (m *MsgAllRewardsResponse) Reset()         { *m = MsgAllRewardsResponse{} }
func (m *MsgAllRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAllRewardsResponse) ProtoMessage()    {}
func (*MsgAllRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_497c523f337df817, []int{3}
}
func (m *MsgAllRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAllRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAllRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAllRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAllRewardsResponse.Merge(m, src)
}
func (m *MsgAllRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAllRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAllRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAllRewardsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgBetAmountRequest)(nil), "game.gamemodule.MsgBetAmountRequest")
	proto.RegisterType((*MsgBetAmountResponse)(nil), "game.gamemodule.MsgBetAmountResponse")
	proto.RegisterType((*MsgAllRewardsRequest)(nil), "game.gamemodule.MsgAllRewardsRequest")
	proto.RegisterType((*MsgAllRewardsResponse)(nil), "game.gamemodule.MsgAllRewardsResponse")
}

func init() { proto.RegisterFile("game/tx.proto", fileDescriptor_497c523f337df817) }

var fileDescriptor_497c523f337df817 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4d, 0x6e, 0xd3, 0x40,
	0x14, 0xc7, 0x33, 0x44, 0x2a, 0xca, 0x94, 0x0f, 0x31, 0x6d, 0x69, 0xc8, 0xc2, 0xae, 0x46, 0x80,
	0xb2, 0xa0, 0x33, 0x4d, 0xa9, 0x84, 0xd4, 0x5d, 0xc2, 0x0e, 0xa9, 0x1b, 0xaf, 0x10, 0x2c, 0x90,
	0x1d, 0x0f, 0x83, 0x21, 0x9e, 0x17, 0xfc, 0xc6, 0xb4, 0xb9, 0x05, 0xe7, 0xe0, 0x0c, 0x1c, 0xa0,
	0xcb, 0x2e, 0x59, 0xb9, 0x28, 0xe1, 0x04, 0x39, 0x01, 0xb2, 0xc7, 0xa1, 0x21, 0xad, 0x94, 0x5d,
	0x37, 0xf6, 0x3c, 0xfd, 0xff, 0xef, 0xe3, 0xf7, 0x34, 0x43, 0xef, 0xeb, 0x30, 0x55, 0xd2, 0x9e,
	0x89, 0x71, 0x06, 0x16, 0xd8, 0xc3, 0x32, 0x14, 0xe5, 0x27, 0x85, 0x38, 0x1f, 0xa9, 0xce, 0xb6,
	0x06, 0x0d, 0x95, 0x26, 0xcb, 0x93, 0xb3, 0x75, 0xbc, 0x21, 0x60, 0x0a, 0x28, 0xa3, 0x10, 0x95,
	0xfc, 0xd6, 0x8b, 0x94, 0x0d, 0x7b, 0x72, 0x08, 0x89, 0x71, 0x3a, 0xff, 0x43, 0xe8, 0xd6, 0x09,
	0xea, 0x81, 0xb2, 0xfd, 0x14, 0x72, 0x63, 0x03, 0xf5, 0x35, 0x57, 0x68, 0xd9, 0x31, 0xbd, 0xf7,
	0x31, 0x83, 0xf4, 0x43, 0x18, 0xc7, 0x99, 0x42, 0x6c, 0x93, 0x3d, 0xd2, 0x6d, 0x0d, 0x76, 0xe7,
	0x85, 0xbf, 0x35, 0x09, 0xd3, 0xd1, 0x31, 0x5f, 0x56, 0x79, 0xb0, 0x59, 0x86, 0x7d, 0x17, 0xb1,
	0x17, 0xf4, 0x6e, 0xa4, 0xac, 0x4d, 0x8c, 0x6e, 0xdf, 0xa9, 0xd2, 0xd8, 0xbc, 0xf0, 0x1f, 0xb8,
	0xb4, 0x5a, 0xe0, 0xc1, 0xc2, 0xc2, 0x86, 0x74, 0x23, 0xac, 0x5a, 0xb7, 0x9b, 0x7b, 0xcd, 0xee,
	0xe6, 0xe1, 0x13, 0xe1, 0x46, 0x16, 0xe5, 0xc8, 0xa2, 0x1e, 0x59, 0xbc, 0x86, 0xc4, 0x0c, 0x0e,
	0xce, 0x0b, 0xbf, 0xf1, 0xe3, 0xd2, 0xef, 0xea, 0xc4, 0x7e, 0xca, 0x23, 0x31, 0x84, 0x54, 0xd6,
	0x7c, 0xee, 0xb7, 0x8f, 0xf1, 0x17, 0x69, 0x27, 0x63, 0x85, 0x55, 0x02, 0x06, 0x75, 0x69, 0xfe,
	0x98, 0x6e, 0xff, 0x4f, 0x89, 0x63, 0x30, 0xa8, 0xf8, 0x25, 0xa9, 0x84, 0xfe, 0x68, 0x14, 0xa8,
	0xd3, 0x30, 0x8b, 0x71, 0xc1, 0x7f, 0x44, 0xa9, 0x85, 0x15, 0xfa, 0x9d, 0x79, 0xe1, 0x3f, 0x72,
	0x18, 0x57, 0x1a, 0x0f, 0x5a, 0x16, 0x96, 0xc8, 0x4f, 0x13, 0x63, 0x54, 0x86, 0xd7, 0xc9, 0x6b,
	0x81, 0x07, 0x0b, 0xcb, 0xed, 0x90, 0xef, 0xd2, 0x9d, 0x15, 0x40, 0x87, 0x7e, 0xf8, 0x93, 0xd0,
	0xe6, 0x09, 0x6a, 0xf6, 0x96, 0xb6, 0xfe, 0xed, 0x85, 0x3d, 0x15, 0x2b, 0xd7, 0x4a, 0xdc, 0x70,
	0x39, 0x3a, 0xcf, 0xd6, 0xb8, 0x5c, 0x07, 0xf6, 0x9e, 0xd2, 0xab, 0xbe, 0xec, 0xc6, 0xa4, 0x6b,
	0x8b, 0xef, 0x3c, 0x5f, 0x67, 0x73, 0xc5, 0x07, 0x6f, 0xce, 0xa7, 0x1e, 0xb9, 0x98, 0x7a, 0xe4,
	0xf7, 0xd4, 0x23, 0xdf, 0x67, 0x5e, 0xe3, 0x62, 0xe6, 0x35, 0x7e, 0xcd, 0xbc, 0xc6, 0xbb, 0x83,
	0xa5, 0x1d, 0x4d, 0x20, 0x37, 0xfa, 0x73, 0x6e, 0x7a, 0xaf, 0x7a, 0x47, 0xd2, 0xd5, 0xdb, 0xb7,
	0x0a, 0xad, 0x3c, 0x93, 0xee, 0x39, 0x95, 0x1b, 0x8b, 0x36, 0xaa, 0xb7, 0xf0, 0xf2, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x51, 0x48, 0xae, 0xe4, 0x63, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	BetAmount(ctx context.Context, in *MsgBetAmountRequest, opts ...grpc.CallOption) (*MsgBetAmountResponse, error)
	AllRewards(ctx context.Context, in *MsgAllRewardsRequest, opts ...grpc.CallOption) (*MsgAllRewardsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) BetAmount(ctx context.Context, in *MsgBetAmountRequest, opts ...grpc.CallOption) (*MsgBetAmountResponse, error) {
	out := new(MsgBetAmountResponse)
	err := c.cc.Invoke(ctx, "/game.gamemodule.Msg/BetAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AllRewards(ctx context.Context, in *MsgAllRewardsRequest, opts ...grpc.CallOption) (*MsgAllRewardsResponse, error) {
	out := new(MsgAllRewardsResponse)
	err := c.cc.Invoke(ctx, "/game.gamemodule.Msg/AllRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	BetAmount(context.Context, *MsgBetAmountRequest) (*MsgBetAmountResponse, error)
	AllRewards(context.Context, *MsgAllRewardsRequest) (*MsgAllRewardsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) BetAmount(ctx context.Context, req *MsgBetAmountRequest) (*MsgBetAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BetAmount not implemented")
}
func (*UnimplementedMsgServer) AllRewards(ctx context.Context, req *MsgAllRewardsRequest) (*MsgAllRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllRewards not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_BetAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBetAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BetAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.gamemodule.Msg/BetAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BetAmount(ctx, req.(*MsgBetAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AllRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAllRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AllRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.gamemodule.Msg/AllRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AllRewards(ctx, req.(*MsgAllRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "game.gamemodule.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BetAmount",
			Handler:    _Msg_BetAmount_Handler,
		},
		{
			MethodName: "AllRewards",
			Handler:    _Msg_AllRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/tx.proto",
}

func (m *MsgBetAmountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBetAmountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBetAmountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Betting) > 0 {
		i -= len(m.Betting)
		copy(dAtA[i:], m.Betting)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Betting)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBetAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBetAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBetAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAllRewardsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAllRewardsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAllRewardsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Winners) > 0 {
		i -= len(m.Winners)
		copy(dAtA[i:], m.Winners)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Winners)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAllRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAllRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAllRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBetAmountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Betting)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgBetAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAllRewardsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Winners)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAllRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBetAmountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBetAmountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBetAmountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Betting", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Betting = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBetAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBetAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBetAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAllRewardsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAllRewardsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAllRewardsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Winners", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Winners = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAllRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAllRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAllRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
